# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'enigma.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1096, 643)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.Reflector = QComboBox(self.centralwidget)
        self.Reflector.addItem("")
        self.Reflector.addItem("")
        self.Reflector.setObjectName(u"Reflector")

        self.gridLayout.addWidget(self.Reflector, 1, 1, 1, 1)

        self.readText = QPlainTextEdit(self.centralwidget)
        self.readText.setObjectName(u"readText")
        self.readText.setUndoRedoEnabled(False)
        self.readText.setReadOnly(True)
        self.readText.setOverwriteMode(True)

        self.gridLayout.addWidget(self.readText, 3, 2, 1, 2)

        self.Plug = QLineEdit(self.centralwidget)
        self.Plug.setObjectName(u"Plug")

        self.gridLayout.addWidget(self.Plug, 0, 1, 1, 2)

        self.Apply = QPushButton(self.centralwidget)
        self.Apply.setObjectName(u"Apply")

        self.gridLayout.addWidget(self.Apply, 2, 1, 1, 1)

        self.gridLayout_3 = QGridLayout()
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.RotorI = QComboBox(self.centralwidget)
        self.RotorI.addItem("")
        self.RotorI.addItem("")
        self.RotorI.addItem("")
        self.RotorI.addItem("")
        self.RotorI.addItem("")
        self.RotorI.setObjectName(u"RotorI")

        self.gridLayout_3.addWidget(self.RotorI, 0, 0, 1, 1)

        self.RotorII = QComboBox(self.centralwidget)
        self.RotorII.addItem("")
        self.RotorII.addItem("")
        self.RotorII.addItem("")
        self.RotorII.addItem("")
        self.RotorII.addItem("")
        self.RotorII.setObjectName(u"RotorII")

        self.gridLayout_3.addWidget(self.RotorII, 0, 1, 1, 1)

        self.RotorIII = QComboBox(self.centralwidget)
        self.RotorIII.addItem("")
        self.RotorIII.addItem("")
        self.RotorIII.addItem("")
        self.RotorIII.addItem("")
        self.RotorIII.addItem("")
        self.RotorIII.setObjectName(u"RotorIII")

        self.gridLayout_3.addWidget(self.RotorIII, 0, 2, 1, 1)

        self.PositionI = QComboBox(self.centralwidget)
        self.PositionI.addItem("")
        self.PositionI.addItem("")
        self.PositionI.addItem("")
        self.PositionI.addItem("")
        self.PositionI.addItem("")
        self.PositionI.addItem("")
        self.PositionI.addItem("")
        self.PositionI.addItem("")
        self.PositionI.addItem("")
        self.PositionI.addItem("")
        self.PositionI.addItem("")
        self.PositionI.addItem("")
        self.PositionI.addItem("")
        self.PositionI.addItem("")
        self.PositionI.addItem("")
        self.PositionI.addItem("")
        self.PositionI.addItem("")
        self.PositionI.addItem("")
        self.PositionI.addItem("")
        self.PositionI.addItem("")
        self.PositionI.addItem("")
        self.PositionI.addItem("")
        self.PositionI.addItem("")
        self.PositionI.addItem("")
        self.PositionI.addItem("")
        self.PositionI.addItem("")
        self.PositionI.setObjectName(u"PositionI")

        self.gridLayout_3.addWidget(self.PositionI, 1, 0, 1, 1)

        self.PositionII = QComboBox(self.centralwidget)
        self.PositionII.addItem("")
        self.PositionII.addItem("")
        self.PositionII.addItem("")
        self.PositionII.addItem("")
        self.PositionII.addItem("")
        self.PositionII.addItem("")
        self.PositionII.addItem("")
        self.PositionII.addItem("")
        self.PositionII.addItem("")
        self.PositionII.addItem("")
        self.PositionII.addItem("")
        self.PositionII.addItem("")
        self.PositionII.addItem("")
        self.PositionII.addItem("")
        self.PositionII.addItem("")
        self.PositionII.addItem("")
        self.PositionII.addItem("")
        self.PositionII.addItem("")
        self.PositionII.addItem("")
        self.PositionII.addItem("")
        self.PositionII.addItem("")
        self.PositionII.addItem("")
        self.PositionII.addItem("")
        self.PositionII.addItem("")
        self.PositionII.addItem("")
        self.PositionII.addItem("")
        self.PositionII.setObjectName(u"PositionII")

        self.gridLayout_3.addWidget(self.PositionII, 1, 1, 1, 1)

        self.PositionIII = QComboBox(self.centralwidget)
        self.PositionIII.addItem("")
        self.PositionIII.addItem("")
        self.PositionIII.addItem("")
        self.PositionIII.addItem("")
        self.PositionIII.addItem("")
        self.PositionIII.addItem("")
        self.PositionIII.addItem("")
        self.PositionIII.addItem("")
        self.PositionIII.addItem("")
        self.PositionIII.addItem("")
        self.PositionIII.addItem("")
        self.PositionIII.addItem("")
        self.PositionIII.addItem("")
        self.PositionIII.addItem("")
        self.PositionIII.addItem("")
        self.PositionIII.addItem("")
        self.PositionIII.addItem("")
        self.PositionIII.addItem("")
        self.PositionIII.addItem("")
        self.PositionIII.addItem("")
        self.PositionIII.addItem("")
        self.PositionIII.addItem("")
        self.PositionIII.addItem("")
        self.PositionIII.addItem("")
        self.PositionIII.addItem("")
        self.PositionIII.addItem("")
        self.PositionIII.setObjectName(u"PositionIII")

        self.gridLayout_3.addWidget(self.PositionIII, 1, 2, 1, 1)

        self.RingSettingI = QComboBox(self.centralwidget)
        self.RingSettingI.addItem("")
        self.RingSettingI.addItem("")
        self.RingSettingI.addItem("")
        self.RingSettingI.addItem("")
        self.RingSettingI.addItem("")
        self.RingSettingI.addItem("")
        self.RingSettingI.addItem("")
        self.RingSettingI.addItem("")
        self.RingSettingI.addItem("")
        self.RingSettingI.addItem("")
        self.RingSettingI.addItem("")
        self.RingSettingI.addItem("")
        self.RingSettingI.addItem("")
        self.RingSettingI.addItem("")
        self.RingSettingI.addItem("")
        self.RingSettingI.addItem("")
        self.RingSettingI.addItem("")
        self.RingSettingI.addItem("")
        self.RingSettingI.addItem("")
        self.RingSettingI.addItem("")
        self.RingSettingI.addItem("")
        self.RingSettingI.addItem("")
        self.RingSettingI.addItem("")
        self.RingSettingI.addItem("")
        self.RingSettingI.addItem("")
        self.RingSettingI.addItem("")
        self.RingSettingI.setObjectName(u"RingSettingI")

        self.gridLayout_3.addWidget(self.RingSettingI, 2, 0, 1, 1)

        self.RingSettingII = QComboBox(self.centralwidget)
        self.RingSettingII.addItem("")
        self.RingSettingII.addItem("")
        self.RingSettingII.addItem("")
        self.RingSettingII.addItem("")
        self.RingSettingII.addItem("")
        self.RingSettingII.addItem("")
        self.RingSettingII.addItem("")
        self.RingSettingII.addItem("")
        self.RingSettingII.addItem("")
        self.RingSettingII.addItem("")
        self.RingSettingII.addItem("")
        self.RingSettingII.addItem("")
        self.RingSettingII.addItem("")
        self.RingSettingII.addItem("")
        self.RingSettingII.addItem("")
        self.RingSettingII.addItem("")
        self.RingSettingII.addItem("")
        self.RingSettingII.addItem("")
        self.RingSettingII.addItem("")
        self.RingSettingII.addItem("")
        self.RingSettingII.addItem("")
        self.RingSettingII.addItem("")
        self.RingSettingII.addItem("")
        self.RingSettingII.addItem("")
        self.RingSettingII.addItem("")
        self.RingSettingII.addItem("")
        self.RingSettingII.setObjectName(u"RingSettingII")

        self.gridLayout_3.addWidget(self.RingSettingII, 2, 1, 1, 1)

        self.RingSettingIII = QComboBox(self.centralwidget)
        self.RingSettingIII.addItem("")
        self.RingSettingIII.addItem("")
        self.RingSettingIII.addItem("")
        self.RingSettingIII.addItem("")
        self.RingSettingIII.addItem("")
        self.RingSettingIII.addItem("")
        self.RingSettingIII.addItem("")
        self.RingSettingIII.addItem("")
        self.RingSettingIII.addItem("")
        self.RingSettingIII.addItem("")
        self.RingSettingIII.addItem("")
        self.RingSettingIII.addItem("")
        self.RingSettingIII.addItem("")
        self.RingSettingIII.addItem("")
        self.RingSettingIII.addItem("")
        self.RingSettingIII.addItem("")
        self.RingSettingIII.addItem("")
        self.RingSettingIII.addItem("")
        self.RingSettingIII.addItem("")
        self.RingSettingIII.addItem("")
        self.RingSettingIII.addItem("")
        self.RingSettingIII.addItem("")
        self.RingSettingIII.addItem("")
        self.RingSettingIII.addItem("")
        self.RingSettingIII.addItem("")
        self.RingSettingIII.addItem("")
        self.RingSettingIII.setObjectName(u"RingSettingIII")

        self.gridLayout_3.addWidget(self.RingSettingIII, 2, 2, 1, 1)


        self.gridLayout.addLayout(self.gridLayout_3, 0, 0, 3, 1)

        self.Reset = QPushButton(self.centralwidget)
        self.Reset.setObjectName(u"Reset")

        self.gridLayout.addWidget(self.Reset, 0, 3, 1, 1)

        self.writeText = QPlainTextEdit(self.centralwidget)
        self.writeText.setObjectName(u"writeText")
        self.writeText.setOverwriteMode(True)

        self.gridLayout.addWidget(self.writeText, 3, 0, 1, 2)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1096, 30))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"EnigmaSimulator", None))
        self.Reflector.setItemText(0, QCoreApplication.translate("MainWindow", u"UKW-B", None))
        self.Reflector.setItemText(1, QCoreApplication.translate("MainWindow", u"UKW-C", None))

        self.readText.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Here comes enigma encryption...", None))
        self.Plug.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter plugboard settings here...", None))
        self.Apply.setText(QCoreApplication.translate("MainWindow", u"Apply Changes", None))
        self.RotorI.setItemText(0, QCoreApplication.translate("MainWindow", u"I", None))
        self.RotorI.setItemText(1, QCoreApplication.translate("MainWindow", u"II", None))
        self.RotorI.setItemText(2, QCoreApplication.translate("MainWindow", u"III", None))
        self.RotorI.setItemText(3, QCoreApplication.translate("MainWindow", u"IV", None))
        self.RotorI.setItemText(4, QCoreApplication.translate("MainWindow", u"V", None))

        self.RotorII.setItemText(0, QCoreApplication.translate("MainWindow", u"II", None))
        self.RotorII.setItemText(1, QCoreApplication.translate("MainWindow", u"I", None))
        self.RotorII.setItemText(2, QCoreApplication.translate("MainWindow", u"III", None))
        self.RotorII.setItemText(3, QCoreApplication.translate("MainWindow", u"IV", None))
        self.RotorII.setItemText(4, QCoreApplication.translate("MainWindow", u"V", None))

        self.RotorIII.setItemText(0, QCoreApplication.translate("MainWindow", u"III", None))
        self.RotorIII.setItemText(1, QCoreApplication.translate("MainWindow", u"I", None))
        self.RotorIII.setItemText(2, QCoreApplication.translate("MainWindow", u"II", None))
        self.RotorIII.setItemText(3, QCoreApplication.translate("MainWindow", u"IV", None))
        self.RotorIII.setItemText(4, QCoreApplication.translate("MainWindow", u"V", None))

        self.PositionI.setItemText(0, QCoreApplication.translate("MainWindow", u"A", None))
        self.PositionI.setItemText(1, QCoreApplication.translate("MainWindow", u"B", None))
        self.PositionI.setItemText(2, QCoreApplication.translate("MainWindow", u"C", None))
        self.PositionI.setItemText(3, QCoreApplication.translate("MainWindow", u"D", None))
        self.PositionI.setItemText(4, QCoreApplication.translate("MainWindow", u"E", None))
        self.PositionI.setItemText(5, QCoreApplication.translate("MainWindow", u"F", None))
        self.PositionI.setItemText(6, QCoreApplication.translate("MainWindow", u"G", None))
        self.PositionI.setItemText(7, QCoreApplication.translate("MainWindow", u"H", None))
        self.PositionI.setItemText(8, QCoreApplication.translate("MainWindow", u"I", None))
        self.PositionI.setItemText(9, QCoreApplication.translate("MainWindow", u"J", None))
        self.PositionI.setItemText(10, QCoreApplication.translate("MainWindow", u"K", None))
        self.PositionI.setItemText(11, QCoreApplication.translate("MainWindow", u"L", None))
        self.PositionI.setItemText(12, QCoreApplication.translate("MainWindow", u"M", None))
        self.PositionI.setItemText(13, QCoreApplication.translate("MainWindow", u"N", None))
        self.PositionI.setItemText(14, QCoreApplication.translate("MainWindow", u"O", None))
        self.PositionI.setItemText(15, QCoreApplication.translate("MainWindow", u"P", None))
        self.PositionI.setItemText(16, QCoreApplication.translate("MainWindow", u"Q", None))
        self.PositionI.setItemText(17, QCoreApplication.translate("MainWindow", u"R", None))
        self.PositionI.setItemText(18, QCoreApplication.translate("MainWindow", u"S", None))
        self.PositionI.setItemText(19, QCoreApplication.translate("MainWindow", u"T", None))
        self.PositionI.setItemText(20, QCoreApplication.translate("MainWindow", u"U", None))
        self.PositionI.setItemText(21, QCoreApplication.translate("MainWindow", u"V", None))
        self.PositionI.setItemText(22, QCoreApplication.translate("MainWindow", u"W", None))
        self.PositionI.setItemText(23, QCoreApplication.translate("MainWindow", u"X", None))
        self.PositionI.setItemText(24, QCoreApplication.translate("MainWindow", u"Y", None))
        self.PositionI.setItemText(25, QCoreApplication.translate("MainWindow", u"Z", None))

        self.PositionII.setItemText(0, QCoreApplication.translate("MainWindow", u"A", None))
        self.PositionII.setItemText(1, QCoreApplication.translate("MainWindow", u"B", None))
        self.PositionII.setItemText(2, QCoreApplication.translate("MainWindow", u"C", None))
        self.PositionII.setItemText(3, QCoreApplication.translate("MainWindow", u"D", None))
        self.PositionII.setItemText(4, QCoreApplication.translate("MainWindow", u"E", None))
        self.PositionII.setItemText(5, QCoreApplication.translate("MainWindow", u"F", None))
        self.PositionII.setItemText(6, QCoreApplication.translate("MainWindow", u"G", None))
        self.PositionII.setItemText(7, QCoreApplication.translate("MainWindow", u"H", None))
        self.PositionII.setItemText(8, QCoreApplication.translate("MainWindow", u"I", None))
        self.PositionII.setItemText(9, QCoreApplication.translate("MainWindow", u"J", None))
        self.PositionII.setItemText(10, QCoreApplication.translate("MainWindow", u"K", None))
        self.PositionII.setItemText(11, QCoreApplication.translate("MainWindow", u"L", None))
        self.PositionII.setItemText(12, QCoreApplication.translate("MainWindow", u"M", None))
        self.PositionII.setItemText(13, QCoreApplication.translate("MainWindow", u"N", None))
        self.PositionII.setItemText(14, QCoreApplication.translate("MainWindow", u"O", None))
        self.PositionII.setItemText(15, QCoreApplication.translate("MainWindow", u"P", None))
        self.PositionII.setItemText(16, QCoreApplication.translate("MainWindow", u"Q", None))
        self.PositionII.setItemText(17, QCoreApplication.translate("MainWindow", u"R", None))
        self.PositionII.setItemText(18, QCoreApplication.translate("MainWindow", u"S", None))
        self.PositionII.setItemText(19, QCoreApplication.translate("MainWindow", u"T", None))
        self.PositionII.setItemText(20, QCoreApplication.translate("MainWindow", u"U", None))
        self.PositionII.setItemText(21, QCoreApplication.translate("MainWindow", u"V", None))
        self.PositionII.setItemText(22, QCoreApplication.translate("MainWindow", u"W", None))
        self.PositionII.setItemText(23, QCoreApplication.translate("MainWindow", u"X", None))
        self.PositionII.setItemText(24, QCoreApplication.translate("MainWindow", u"Y", None))
        self.PositionII.setItemText(25, QCoreApplication.translate("MainWindow", u"Z", None))

        self.PositionIII.setItemText(0, QCoreApplication.translate("MainWindow", u"A", None))
        self.PositionIII.setItemText(1, QCoreApplication.translate("MainWindow", u"B", None))
        self.PositionIII.setItemText(2, QCoreApplication.translate("MainWindow", u"C", None))
        self.PositionIII.setItemText(3, QCoreApplication.translate("MainWindow", u"D", None))
        self.PositionIII.setItemText(4, QCoreApplication.translate("MainWindow", u"E", None))
        self.PositionIII.setItemText(5, QCoreApplication.translate("MainWindow", u"F", None))
        self.PositionIII.setItemText(6, QCoreApplication.translate("MainWindow", u"G", None))
        self.PositionIII.setItemText(7, QCoreApplication.translate("MainWindow", u"H", None))
        self.PositionIII.setItemText(8, QCoreApplication.translate("MainWindow", u"I", None))
        self.PositionIII.setItemText(9, QCoreApplication.translate("MainWindow", u"J", None))
        self.PositionIII.setItemText(10, QCoreApplication.translate("MainWindow", u"K", None))
        self.PositionIII.setItemText(11, QCoreApplication.translate("MainWindow", u"L", None))
        self.PositionIII.setItemText(12, QCoreApplication.translate("MainWindow", u"M", None))
        self.PositionIII.setItemText(13, QCoreApplication.translate("MainWindow", u"N", None))
        self.PositionIII.setItemText(14, QCoreApplication.translate("MainWindow", u"O", None))
        self.PositionIII.setItemText(15, QCoreApplication.translate("MainWindow", u"P", None))
        self.PositionIII.setItemText(16, QCoreApplication.translate("MainWindow", u"Q", None))
        self.PositionIII.setItemText(17, QCoreApplication.translate("MainWindow", u"R", None))
        self.PositionIII.setItemText(18, QCoreApplication.translate("MainWindow", u"S", None))
        self.PositionIII.setItemText(19, QCoreApplication.translate("MainWindow", u"T", None))
        self.PositionIII.setItemText(20, QCoreApplication.translate("MainWindow", u"U", None))
        self.PositionIII.setItemText(21, QCoreApplication.translate("MainWindow", u"V", None))
        self.PositionIII.setItemText(22, QCoreApplication.translate("MainWindow", u"W", None))
        self.PositionIII.setItemText(23, QCoreApplication.translate("MainWindow", u"X", None))
        self.PositionIII.setItemText(24, QCoreApplication.translate("MainWindow", u"Y", None))
        self.PositionIII.setItemText(25, QCoreApplication.translate("MainWindow", u"Z", None))

        self.RingSettingI.setItemText(0, QCoreApplication.translate("MainWindow", u"0", None))
        self.RingSettingI.setItemText(1, QCoreApplication.translate("MainWindow", u"1", None))
        self.RingSettingI.setItemText(2, QCoreApplication.translate("MainWindow", u"2", None))
        self.RingSettingI.setItemText(3, QCoreApplication.translate("MainWindow", u"3", None))
        self.RingSettingI.setItemText(4, QCoreApplication.translate("MainWindow", u"4", None))
        self.RingSettingI.setItemText(5, QCoreApplication.translate("MainWindow", u"5", None))
        self.RingSettingI.setItemText(6, QCoreApplication.translate("MainWindow", u"6", None))
        self.RingSettingI.setItemText(7, QCoreApplication.translate("MainWindow", u"7", None))
        self.RingSettingI.setItemText(8, QCoreApplication.translate("MainWindow", u"8", None))
        self.RingSettingI.setItemText(9, QCoreApplication.translate("MainWindow", u"9", None))
        self.RingSettingI.setItemText(10, QCoreApplication.translate("MainWindow", u"10", None))
        self.RingSettingI.setItemText(11, QCoreApplication.translate("MainWindow", u"11", None))
        self.RingSettingI.setItemText(12, QCoreApplication.translate("MainWindow", u"12", None))
        self.RingSettingI.setItemText(13, QCoreApplication.translate("MainWindow", u"13", None))
        self.RingSettingI.setItemText(14, QCoreApplication.translate("MainWindow", u"14", None))
        self.RingSettingI.setItemText(15, QCoreApplication.translate("MainWindow", u"15", None))
        self.RingSettingI.setItemText(16, QCoreApplication.translate("MainWindow", u"16", None))
        self.RingSettingI.setItemText(17, QCoreApplication.translate("MainWindow", u"17", None))
        self.RingSettingI.setItemText(18, QCoreApplication.translate("MainWindow", u"18", None))
        self.RingSettingI.setItemText(19, QCoreApplication.translate("MainWindow", u"19", None))
        self.RingSettingI.setItemText(20, QCoreApplication.translate("MainWindow", u"20", None))
        self.RingSettingI.setItemText(21, QCoreApplication.translate("MainWindow", u"21", None))
        self.RingSettingI.setItemText(22, QCoreApplication.translate("MainWindow", u"22", None))
        self.RingSettingI.setItemText(23, QCoreApplication.translate("MainWindow", u"23", None))
        self.RingSettingI.setItemText(24, QCoreApplication.translate("MainWindow", u"24", None))
        self.RingSettingI.setItemText(25, QCoreApplication.translate("MainWindow", u"25", None))

        self.RingSettingII.setItemText(0, QCoreApplication.translate("MainWindow", u"0", None))
        self.RingSettingII.setItemText(1, QCoreApplication.translate("MainWindow", u"1", None))
        self.RingSettingII.setItemText(2, QCoreApplication.translate("MainWindow", u"2", None))
        self.RingSettingII.setItemText(3, QCoreApplication.translate("MainWindow", u"3", None))
        self.RingSettingII.setItemText(4, QCoreApplication.translate("MainWindow", u"4", None))
        self.RingSettingII.setItemText(5, QCoreApplication.translate("MainWindow", u"5", None))
        self.RingSettingII.setItemText(6, QCoreApplication.translate("MainWindow", u"6", None))
        self.RingSettingII.setItemText(7, QCoreApplication.translate("MainWindow", u"7", None))
        self.RingSettingII.setItemText(8, QCoreApplication.translate("MainWindow", u"8", None))
        self.RingSettingII.setItemText(9, QCoreApplication.translate("MainWindow", u"9", None))
        self.RingSettingII.setItemText(10, QCoreApplication.translate("MainWindow", u"10", None))
        self.RingSettingII.setItemText(11, QCoreApplication.translate("MainWindow", u"11", None))
        self.RingSettingII.setItemText(12, QCoreApplication.translate("MainWindow", u"12", None))
        self.RingSettingII.setItemText(13, QCoreApplication.translate("MainWindow", u"13", None))
        self.RingSettingII.setItemText(14, QCoreApplication.translate("MainWindow", u"14", None))
        self.RingSettingII.setItemText(15, QCoreApplication.translate("MainWindow", u"15", None))
        self.RingSettingII.setItemText(16, QCoreApplication.translate("MainWindow", u"16", None))
        self.RingSettingII.setItemText(17, QCoreApplication.translate("MainWindow", u"17", None))
        self.RingSettingII.setItemText(18, QCoreApplication.translate("MainWindow", u"18", None))
        self.RingSettingII.setItemText(19, QCoreApplication.translate("MainWindow", u"19", None))
        self.RingSettingII.setItemText(20, QCoreApplication.translate("MainWindow", u"20", None))
        self.RingSettingII.setItemText(21, QCoreApplication.translate("MainWindow", u"21", None))
        self.RingSettingII.setItemText(22, QCoreApplication.translate("MainWindow", u"22", None))
        self.RingSettingII.setItemText(23, QCoreApplication.translate("MainWindow", u"23", None))
        self.RingSettingII.setItemText(24, QCoreApplication.translate("MainWindow", u"24", None))
        self.RingSettingII.setItemText(25, QCoreApplication.translate("MainWindow", u"25", None))

        self.RingSettingIII.setItemText(0, QCoreApplication.translate("MainWindow", u"0", None))
        self.RingSettingIII.setItemText(1, QCoreApplication.translate("MainWindow", u"1", None))
        self.RingSettingIII.setItemText(2, QCoreApplication.translate("MainWindow", u"2", None))
        self.RingSettingIII.setItemText(3, QCoreApplication.translate("MainWindow", u"3", None))
        self.RingSettingIII.setItemText(4, QCoreApplication.translate("MainWindow", u"4", None))
        self.RingSettingIII.setItemText(5, QCoreApplication.translate("MainWindow", u"5", None))
        self.RingSettingIII.setItemText(6, QCoreApplication.translate("MainWindow", u"6", None))
        self.RingSettingIII.setItemText(7, QCoreApplication.translate("MainWindow", u"7", None))
        self.RingSettingIII.setItemText(8, QCoreApplication.translate("MainWindow", u"8", None))
        self.RingSettingIII.setItemText(9, QCoreApplication.translate("MainWindow", u"9", None))
        self.RingSettingIII.setItemText(10, QCoreApplication.translate("MainWindow", u"10", None))
        self.RingSettingIII.setItemText(11, QCoreApplication.translate("MainWindow", u"11", None))
        self.RingSettingIII.setItemText(12, QCoreApplication.translate("MainWindow", u"12", None))
        self.RingSettingIII.setItemText(13, QCoreApplication.translate("MainWindow", u"13", None))
        self.RingSettingIII.setItemText(14, QCoreApplication.translate("MainWindow", u"14", None))
        self.RingSettingIII.setItemText(15, QCoreApplication.translate("MainWindow", u"15", None))
        self.RingSettingIII.setItemText(16, QCoreApplication.translate("MainWindow", u"16", None))
        self.RingSettingIII.setItemText(17, QCoreApplication.translate("MainWindow", u"17", None))
        self.RingSettingIII.setItemText(18, QCoreApplication.translate("MainWindow", u"18", None))
        self.RingSettingIII.setItemText(19, QCoreApplication.translate("MainWindow", u"19", None))
        self.RingSettingIII.setItemText(20, QCoreApplication.translate("MainWindow", u"20", None))
        self.RingSettingIII.setItemText(21, QCoreApplication.translate("MainWindow", u"21", None))
        self.RingSettingIII.setItemText(22, QCoreApplication.translate("MainWindow", u"22", None))
        self.RingSettingIII.setItemText(23, QCoreApplication.translate("MainWindow", u"23", None))
        self.RingSettingIII.setItemText(24, QCoreApplication.translate("MainWindow", u"24", None))
        self.RingSettingIII.setItemText(25, QCoreApplication.translate("MainWindow", u"25", None))

        self.Reset.setText(QCoreApplication.translate("MainWindow", u"Reset", None))
        self.writeText.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Write text to encipher... ", None))
    # retranslateUi

